name: One Time 🕒
description: Add a new one-time freeleech event
labels: [one-time]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for adding a freeleech event!**

        Please fill out the fields below. For dates, please use the format YYYY.MM.DD. So September 1st 2025 would be 2025.09.01.

  - type: input
    attributes:
      label: Tracker
      description: The name of the tracker (either long name or short code)
      placeholder: PTP

  - type: input
    attributes:
      label: Freeleech start
      description: When the freeleech event will start / started (If you don't know provide an estimation instead)
      placeholder: 2025.09.01 00:00:00 UTC

  - type: input
    attributes:
      label: Freeleech end
      description: When the freeleech event will end
      placeholder: 2025.09.10 00:00:00 UTC

  - type: dropdown
    attributes:
      label: Double upload?
      description: Is double upload set for this event?
      options:
        - "No"
        - "Yes"
      default: 0

  - type: textarea
    attributes:
      label: Extra
      description: If there's anything else to know, feel free to add it here! Usually this is left empty.
